### ISSUE TITLE
Navbar eklenmeli

### ISSUE THREAD

**Issue by beyzaerkan** [anchovycation/pingu-front-end#10]

**Comment by beyzaerkan** [comment]
**@saracalihan** Navbar yerine bence oda isminin yanına , youtube url girişi yapılan input, tam ekran , tiyatro modu ve ayarlar ikonları gelebilir. Anasayfaya dönmek için de yine ok ikonu eklenerek dönülebilir. Ne diyorsun?

![Untitled (2)](https://user-images.githubusercontent.com/76122007/197012339-24df6eba-54b6-4ade-aab7-22c158b787c6.png)

**Comment by saracalihan** [comment]
> **@saracalihan** Navbar yerine bence oda isminin yanına , youtube url girişi yapılan input, tam ekran , tiyatro modu ve ayarlar ikonları gelebilir. Anasayfaya dönmek için de yine ok ikonu eklenerek dönülebilir. Ne diyorsun?
> 
> ![Untitled (2)](https://user-images.githubusercontent.com/76122007/197012339-24df6eba-54b6-4ade-aab7-22c158b787c6.png)

Bence de uygun böyle daha iyi olur. Logo markamızı temsil ediyor ama bir o kadar da yer kaplıyor, illa ki olsun diyorsak sayfa ilk yüknediğinde 3 5 saniye duracak ve sonra yok olacak bir şekilde bir bar koyabiliriz bu dediğinin üstüne
