### ISSUE TITLE
Tasarım dokümanı tamamlanmalı

### ISSUE THREAD

**Issue by saracalihan** [anchovycation/pingu-front-end#3]
Renk paleti oluşturulmalı ve Figma üzerindeki tasarımlar hakkında karar alınmalı.

**Comment by saracalihan** [comment]
![Screenshot_20220128_204313](https://user-images.githubusercontent.com/56413673/151595896-30cb55ce-f21a-44eb-b09b-a6398bf07772.png)

**Comment by beyzaerkan** [comment]
### Ana palet
![AdobeColor-pingu](https://user-images.githubusercontent.com/76122007/151597143-76283c20-ba08-400a-a36d-1d0f85c4d6e6.jpeg)

### Diğer Palet
![AdobeColor-pingu_ornek_1](https://user-images.githubusercontent.com/76122007/151597251-911c1f12-e5c7-4958-8408-2754d4a6dbf0.jpeg)
