### ISSUE TITLE
olan bir odaya katılmak istendiğinde user bilgileri yanlış geliyor

### ISSUE THREAD

**Issue by beyzaerkan** [anchovycation/pingu-front-end#68]
`JoinRoomChecker` komponentinde user bilgileri oda içerisinden alınıyor. Mongo'ya geçtikten sonra user bilgileri ayrı olarak ve aynı zamanda `room` içerisinde userların sadece id'si tutulacak şeklinde düzenlendi.

Öneri:
- Room içinde tutulan userın id'sine göre user çağırılabilir.

**Comment by saracalihan** [comment]
**fixed** https://github.com/anchovycation/pingu-api/pull/68
